title: toctocMarseille - Holiday Planner
author:
  name: Uli Straub
  email: 'uli.straub@kontinui.de'
metadata:
    refresh: 30
    generator: 'Grav'
    description: ''
    keywords: 'Holiday Planner'
    author: 'Uli Straub'
    robots: 'noindex, nofollow'
taxonomies: [category,tag,example]
blog:
  route: '/blog'      
# Site settings
title: toctocMarseille.com - Tailor-made holidays
email: toctocMarseille@gmail.com
description: ''

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  -  url: 'https://www.facebook.com/toctocMarseille'
     icon: facebook
  -  url: 'https://www.instagram.com/toctocmarseille/'
     icon: instagram
  -  url: 'https://twitter.com/toctocmarseille'
     icon: twitter
  -  url: 'blog.rss'
     icon: rss

copyright: 
  line1: Untitled
  line2: Design:
  url: http://www.kontinui.de
  url_label: Kontinui
    
logo:
  text1: "tictactoc"
  text2: "by Kontinui"

# Main Menu
# menu:
# - text: "submenu"
#   submenu:
#     - text: "info"
#       link: "#"
#     - text: "profile"
#       link: "#"  
#     - text: "news"
#       link: "#"
#       submenu:
#         - text: "fresh"
#           link: "#"
#         - text: "archive"
#           link: "#"  
#   link: "#" 
